server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: appointment-service
            uri: lb://appointment-service
            predicates:
              - Path=/appointment/**
          - id: patient-service
            uri: lb://patient-service
            predicates:
              - Path=/patient/**
  config:
    import: "optional:configserver:http://localhost:8088"